### ISSUE TITLE
libvirt formula has changed

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/salt-virt-formula#2]
state should be:
```
include:
  - libvirt.install

salt_virt_keys:
  libvirt.keys:
    - require:
      - pkg: libvirt.install
```
