### ISSUE TITLE
libvirt.keys should be virt.keys

### ISSUE THREAD

**Issue by p-thurner** [saltstack-formulas/salt-virt-formula#4]
I found this to be wrong in the doc and this formula: 

https://docs.saltstack.com/en/latest/topics/tutorials/cloud_controller.html#setting-up-hypervisors

For me only this works:

```
libvirt_setup_keys:
  virt.keys:
    - name: libvirt_keys
```

Using

```
libvirt_setup_keys:
  libvirt.keys:
    - name: libvirt_keys
```

Gives me:

```
          ID: libvirt_setup_keys
    Function: libvirt.keys
      Result: False
     Comment: State 'libvirt.keys' was not found in SLS 'libvirt'
              Reason: 'libvirt.keys' is not available.
     Changes:   
```
